[package]
name = "lexer"
version.workspace = true
edition.workspace = true

[dependencies]
phf = { version = "0.11.3", features = ["macros"] }
string_cache = "0.8.4"

[dev-dependencies]
pretty_assertions = "1.4.0"
